<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Bangplanix.Engine</RootNamespace>
    <AssemblyName>Bangplanix.Engine</AssemblyName>
    <Description>Bangplanix SkiaSharp 2D Vector Rendering Engine, HarfBuzz Text Shaping, and Bands</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bangplanix.Core\Bangplanix.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="SkiaSharp.HarfBuzz" />
    <PackageReference Include="HarfBuzzSharp" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" />
    <PackageReference Include="ZXing.Net" />
    <PackageReference Include="QRCoder" />
  </ItemGroup>
</Project>
