using System;
using System.Net;
using System.Text;
using Bangplanix.Core.Models;

namespace Bangplanix.Engine.Accessibility;

/// <summary>
/// Exporter for Semantic HTML5 + WAI-ARIA 1.2 Accessible Web Reports.
/// </summary>
public static class AccessibleHtmlExporter
{
    public static string ExportToSemanticHtml(
        ReportDefinition reportDef,
        PdfStructElement structTree,
        AccessibilityOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(reportDef);
        ArgumentNullException.ThrowIfNull(structTree);

        var opts = options ?? new AccessibilityOptions();
        var sb = new StringBuilder();

        string docTitle = !string.IsNullOrWhiteSpace(opts.DocumentTitle)
            ? opts.DocumentTitle
            : (!string.IsNullOrWhiteSpace(reportDef.Metadata.Title) ? reportDef.Metadata.Title : "Bangplanix Report");

        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine($"<html lang=\"{WebUtility.HtmlEncode(opts.PrimaryLanguage)}\">");
        sb.AppendLine("<head>");
        sb.AppendLine("  <meta charset=\"utf-8\">");
        sb.AppendLine("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.AppendLine($"  <title>{WebUtility.HtmlEncode(docTitle)}</title>");
        sb.AppendLine("  <style>");
        sb.AppendLine("    body { font-family: 'Sarabun', system-ui, -apple-system, sans-serif; line-height: 1.6; color: #1e293b; max-width: 900px; margin: 0 auto; padding: 2rem; }");
        sb.AppendLine("    table { width: 100%; border-collapse: collapse; margin: 1.5rem 0; }");
        sb.AppendLine("    th, td { border: 1px solid #cbd5e1; padding: 0.75rem 1rem; text-align: left; }");
        sb.AppendLine("    th { background-color: #f1f5f9; font-weight: 600; }");
        sb.AppendLine("    figure { margin: 1.5rem 0; text-align: center; }");
        sb.AppendLine("    figcaption { font-size: 0.875rem; color: #64748b; margin-top: 0.5rem; }");
        sb.AppendLine("    .skip-link { position: absolute; top: -40px; left: 0; background: #000; color: #fff; padding: 8px; z-index: 100; }");
        sb.AppendLine("    .skip-link:focus { top: 0; }");
        sb.AppendLine("  </style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("  <a href=\"#main-content\" class=\"skip-link\">Skip to main content</a>");
        sb.AppendLine("  <header role=\"banner\">");
        sb.AppendLine($"    <h1>{WebUtility.HtmlEncode(docTitle)}</h1>");
        sb.AppendLine("  </header>");
        sb.AppendLine("  <main id=\"main-content\" role=\"main\">");

        RenderElement(sb, structTree, 2);

        sb.AppendLine("  </main>");
        sb.AppendLine("  <footer role=\"contentinfo\">");
        sb.AppendLine("    <hr>");
        sb.AppendLine($"    <p><small>Generated by Bangplanix Accessible Reporting Engine (WCAG 2.1 AA / PDF/UA-1 Compliant)</small></p>");
        sb.AppendLine("  </footer>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return sb.ToString();
    }

    private static void RenderElement(StringBuilder sb, PdfStructElement elem, int indent)
    {
        string spaces = new string(' ', indent);

        switch (elem.TagType)
        {
            case PdfTagType.Document:
            case PdfTagType.Section:
                foreach (var child in elem.Children)
                {
                    RenderElement(sb, child, indent);
                }
                break;

            case PdfTagType.H1:
                sb.AppendLine($"{spaces}<h1>{WebUtility.HtmlEncode(elem.ActualText ?? elem.Title ?? string.Empty)}</h1>");
                break;

            case PdfTagType.H2:
                sb.AppendLine($"{spaces}<h2>{WebUtility.HtmlEncode(elem.ActualText ?? elem.Title ?? string.Empty)}</h2>");
                break;

            case PdfTagType.H3:
                sb.AppendLine($"{spaces}<h3>{WebUtility.HtmlEncode(elem.ActualText ?? elem.Title ?? string.Empty)}</h3>");
                break;

            case PdfTagType.H4:
                sb.AppendLine($"{spaces}<h4>{WebUtility.HtmlEncode(elem.ActualText ?? elem.Title ?? string.Empty)}</h4>");
                break;

            case PdfTagType.Paragraph:
                sb.AppendLine($"{spaces}<p>{WebUtility.HtmlEncode(elem.ActualText ?? elem.Title ?? string.Empty)}</p>");
                break;

            case PdfTagType.Table:
                sb.AppendLine($"{spaces}<table role=\"table\">");
                foreach (var child in elem.Children)
                {
                    RenderElement(sb, child, indent + 2);
                }
                sb.AppendLine($"{spaces}</table>");
                break;

            case PdfTagType.TableRow:
                sb.AppendLine($"{spaces}<tr>");
                foreach (var child in elem.Children)
                {
                    RenderElement(sb, child, indent + 2);
                }
                sb.AppendLine($"{spaces}</tr>");
                break;

            case PdfTagType.TableHeader:
                string thScope = elem.Scope == TableScopeType.Row ? " scope=\"row\"" : " scope=\"col\"";
                string thId = !string.IsNullOrWhiteSpace(elem.Id) ? $" id=\"{elem.Id}\"" : "";
                sb.AppendLine($"{spaces}<th{thScope}{thId}>{WebUtility.HtmlEncode(elem.ActualText ?? elem.Title ?? string.Empty)}</th>");
                break;

            case PdfTagType.TableData:
                string tdHeaders = elem.Headers.Count > 0 ? $" headers=\"{string.Join(" ", elem.Headers)}\"" : "";
                string tdId = !string.IsNullOrWhiteSpace(elem.Id) ? $" id=\"{elem.Id}\"" : "";
                sb.AppendLine($"{spaces}<td{tdHeaders}{tdId}>{WebUtility.HtmlEncode(elem.ActualText ?? elem.Title ?? string.Empty)}</td>");
                break;

            case PdfTagType.Figure:
                string alt = !string.IsNullOrWhiteSpace(elem.AltText) ? elem.AltText : "Figure Graphic";
                sb.AppendLine($"{spaces}<figure role=\"img\" aria-label=\"{WebUtility.HtmlEncode(alt)}\">");
                sb.AppendLine($"{spaces}  <div class=\"figure-content\">[{WebUtility.HtmlEncode(alt)}]</div>");
                sb.AppendLine($"{spaces}  <figcaption>{WebUtility.HtmlEncode(alt)}</figcaption>");
                sb.AppendLine($"{spaces}</figure>");
                break;

            case PdfTagType.Artifact:
                // Artifacts are decorative and ignored in accessible document flow
                break;

            default:
                foreach (var child in elem.Children)
                {
                    RenderElement(sb, child, indent);
                }
                break;
        }
    }
}