<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Bangplanix.Client</PackageId>
    <Title>Bangplanix Client SDK (.NET)</Title>
    <Description>Official High-Performance .NET 10 Client SDK for Bangplanix Reporting Engine</Description>
    <PackageTags>reporting;report;crystal-reports;ssrs;pdf;excel;bangplanix;wasm</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bangplanix.Core\Bangplanix.Core.csproj" />
  </ItemGroup>
</Project>