apiVersion: v2
name: bangplanix
description: Enterprise High-Performance Reporting & Document Generation Engine (.NET 10 / Native AOT)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - reporting
  - pdf-generator
  - high-performance
  - enterprise
  - native-aot
home: https://github.com/thabot/bangplanix
sources:
  - https://github.com/thabot/bangplanix
maintainers:
  - name: Bangplanix Team
    email: thabot47@gmail.com
